# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='screenshot',
            new_name='image_url',
        ),
    ]
