# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_auto_20180605_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='project_screenshot',
        ),
    ]
